name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./request payment/pom.xml
          mvn clean package -f ./credit cards/pom.xml
          mvn clean package -f ./cash/pom.xml

      - name: Docker Build and push for RequestPayment
        uses: docker/build-push-action@v4
        with:
          context: ./request payment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/request-payment:latest
            ghcr.io/${{ github.repository }}/request-payment:${{ github.ref_name }}
            
      - name: Docker Build and push for CreditCards
        uses: docker/build-push-action@v4
        with:
          context: ./credit cards
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/credit-cards:latest
            ghcr.io/${{ github.repository }}/credit-cards:${{ github.ref_name }}
            
      - name: Docker Build and push for Cash
        uses: docker/build-push-action@v4
        with:
          context: ./cash
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cash:latest
            ghcr.io/${{ github.repository }}/cash:${{ github.ref_name }}
            
