apiVersion: apps/v1
kind: Deployment
metadata:
  name: request payment
  labels:
    app: request payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request payment
  template:
    metadata:
      labels:
        app: request payment
    spec:
      containers:
        - name: request payment
          image: "username/request payment:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
