---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: request payment
  labels:
    app: request payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request payment
  template:
    metadata:
      labels:
        app: request payment
    spec:
      containers:
        - name: request payment
          image: username/request payment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit cards
  labels:
    app: credit cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit cards
  template:
    metadata:
      labels:
        app: credit cards
    spec:
      containers:
        - name: credit cards
          image: username/credit cards:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash
  labels:
    app: cash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cash
  template:
    metadata:
      labels:
        app: cash
    spec:
      containers:
        - name: cash
          image: username/cash:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: request payment
  labels:
    app: request payment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: request payment


---


apiVersion: v1
kind: Service
metadata:
  name: credit cards
  labels:
    app: credit cards
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: credit cards


---


apiVersion: v1
kind: Service
metadata:
  name: cash
  labels:
    app: cash
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cash

