apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit cards
  labels:
    app: credit cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit cards
  template:
    metadata:
      labels:
        app: credit cards
    spec:
      containers:
        - name: credit cards
          image: "username/credit cards:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
